### ISSUE TITLE
The Image Voxel Normalisation

### ISSUE THREAD

**Issue by jessyblues** [vkola-lab/nmed2024#1]
Before the MRI is sent into the SwinUnetr, I wonder that whether the image voxel value is normalised to [-1, 1], [0, 1] or else ?

**Comment by dlteif** [comment]
Yes, before sending the MRI to the SwinUNETR, it undergoes a series of transformations using the MONAI package for medical imaging, including ensuring the channel dimension goes first and resampling the input MRI into the same pixel dimensions. The last transformation function is min-max normalization which normalizes the input to [0,1] based on the following formula:

$$
x' = \frac{x- min(x)}{(max(x)-min(x))} * (b - a) + a
$$

Where $a$ and $b$ are the new minimum and maximum, respectively. In our case, $\[a,b\] = \[0,1\]$.
