### ISSUE TITLE
deIT missing

### ISSUE THREAD

**Issue by kakou34** [vkola-lab/nmed2024#3]
Hi! 
Thank you a lot for the impressive work! I really enjoyed reading your paper. 
I am trying to run the code on my data but it keeps complaining with this error ModuleNotFoundError: No module named 'models.DeIT'. When I check the code, it seems that indeed this folder does not exist. Could you please help solving this issue? Thanks in advance

**Comment by sahanakowshik** [comment]
Hi, could you please share the complete error log?
