### ISSUE TITLE
SwinUNETR Weights 

### ISSUE THREAD

**Issue by kakou34** [vkola-lab/nmed2024#4]
Hi! 
Thank you very much for the impressive work! 

I was curious to know whether you fine-tuned the SwinUNETR model on the Dementia dataset that you built for the paper or you just used the pre-trained weights provided by the SwinUNETR authors (CVPR paper).

Thank you in advance!

**Comment by dlteif** [comment]
Thank you for your interest in our work!

We ended up using the pre-trained weights provided by the SwinUNETR authors to generate the image embeddings to feed into the transformer. You can download the weights from the SwinUNETR GitHub repository.
