### ISSUE TITLE
How can i get the DeIT module?

### ISSUE THREAD

**Issue by liulangdexiaoxin** [vkola-lab/nmed2024#5]
![微信图片_20241110143117](https://github.com/user-attachments/assets/452ca7df-53d5-4713-bfc8-01294a017478)
ModuleNotFoundError: No module named 'models.DeIT'

**Comment by dlteif** [comment]
Thank you for bringing this error to our attention! We just removed the unused DeIT module import. Please pull the latest changes and get back to us if there are any further issues. Thanks.
