### ISSUE TITLE
Get MRI embedding problem

### ISSUE THREAD

**Issue by GGGODs** [vkola-lab/nmed2024#6]
when getting the MRI embedding,The image_size parameter in SWIN UNETR requires dimensions to be divisible by2**5= 32. However, your input image size is 182*218*182 which will cause an error when passed into the model. So how can I fix it?

**Comment by dlteif** [comment]
Thanks for your interest in our work!
The image size (182x218x182) is for the DenseNet imaging model. For the SwinUNETR model, the image size you need to specify is 128x128x128. 
To generate the MRI embeddings, you can pass --img_net=SwinUNETR and --img_mode=2 in train.sh
