### ISSUE TITLE
Patient distribution for training and testing

### ISSUE THREAD

**Issue by sarro54** [vkola-lab/nmed2024#7]
Thank you for your valuable research and contributions. Could you please provide details about the patient distribution used for training and testing in your experiments for all datasets?

**Comment by sahanakowshik** [comment]
Hi @sarro54, we have included the patient IDs used for training and testing under [data/datasets](https://github.com/vkola-lab/nmed2024/tree/main/data/datasets). Please refer to supplementary tables S2-S5 of our [paper](https://static-content.springer.com/esm/art%3A10.1038%2Fs41591-024-03118-z/MediaObjects/41591_2024_3118_MOESM1_ESM.pdf) for detailed information of the fields we used for each dataset.
